# Curriculum vitae

## Over mij

Gemotiveerde Life Science studente met een interesse in de BLA BLA BLA.
Brede kennis over moleculaire, biochemische en microbiologische laboratoriumtechnieken.
Altijd bereid om nieuwe vaardigheden te leren en kennis op te doen.

---

## Werkervaring

Medewerker schoonmaak, UMC en Randstad, Utrecht 		          
September 2020 – September 2023

Dagelijks contact met patiënten en het aanspreekpunt voor een schone en steriele omgeving op plekken zoals de Intensive Care, het OK-centrum en de poliklinieken.

Caissière, Albert Heijn, Utrecht
Mei 2020 – Oktober 2020

Dagelijks contact met klanten en het aanspreekpunt voor klantenservice. 

---

## Opleiding
Biologie en Medisch Laboratoriumonderzoek (Life Science)

Hogeschool Utrecht, Utrecht 		 

September 2021 – Februari 2026

-	Afstudeerrichting: Microbiologie

- Minor: Data Science For Biology


Hoger Algemeen Voortgezet Onderwijs (HAVO)

St. Bonifatiuscollege, Utrecht

September 2015 – Juli 2020

-	Natuur en Gezondheid


---

## Overig

Vaardigheden

- Laboratoriumveiligheid

- Laboratorium technieken

- Zelfstandig werken

- In teamverband werken


Talen

- Nederlands (moedertaal)

- Engels (B2 niveau)

Kenmerken

- IJverig

- Leergierig

- Initiatief nemend

- Secuur

---
