# Het effect van transposons op biologische processen van de E. coli
 
Voor mijn vrije opdracht wil ik het effect van transposons op bacteriën onderzoeken. Aangezien mijn afstudeerrichting microbiologie is, sluit dit onderwerp er goed bij aan. De ruwe data die ik zal gebruiken komt van GEO, onder de accession GSE197084. In dit onderzoek werd het effect van transposons op de virulentie van Escherichia coli bestudeerd. Het genoom van E. coli werd eerst gesequenced, waarna transposons werden geïntroduceerd. De gemuteerde bacteriën werden vervolgens geïmplanteerd in de hersenen, milt en longen van muizen om de effecten van de gemuteerde bacteriën in verschillende omgevingen te bestuderen. Na de infectie werden de bacteriën opnieuw gesequenced.

Mijn doel is om de data van de E. coli voor en na transposon-insertie te vergelijken en een bredere analyse te maken van de genen en biologische processen die mogelijk zijn beïnvloed door de transposons. Ik ben niet alleen geïnteresseerd in virulentie-gerelateerde genen, maar wil ook onderzoeken hoe andere genetische processen mogelijk zijn aangepast door de transposons.

Ik zal de analyse deels uitvoeren met technieken die ik heb geleerd tijdens de DAUR2-cursus, zoals genexpressie-analyse en GO-term enrichment, en daarnaast andere methoden onderzoeken die me helpen om een compleet beeld te krijgen van de veranderingen in het E. coli-genoom. Aangezien de bacteriën in verschillende organen van de muizen zijn geïmplanteerd, lijkt het me ook interessant om de verschillen in genetische veranderingen te onderzoeken afhankelijk van het orgaan waar de bacteriën werden geïmplanteerd. 