# Looking ahead

**Where do I want to be in ~2 years time?**

I’m currently in the final phase of my Life Sciences degree at Hogeschool Utrecht and will be graduating soon. In about two years, I hope to be working in a research-oriented lab environment, ideally in the field of microbiology. I want to be in a position where I can combine hands-on lab work with data analysis, particularly involving next-generation sequencing (NGS), so I can continue building on both my experimental and data science skills.

By that time, I aim to have gained valuable experience in the field and a better understanding of what type of work suits me best. If I come across a master’s program that really fits my interests, I might decide to continue studying, but for now, my goal is to focus on growing professionally and learning as much as possible in a real research setting.

---

**How am I doing now with respect to this goal?**

I’m well on my way to achieving my goals. Looking back, I sometimes don’t realize how much I’ve learned over the past few years, but I often surprise myself with what I’m capable of. I’m currently doing my research internship, the final phase of my studies before graduation, where I’m working with NGS data and focusing on further developing my data science and bioinformatics skills.

---

**What would be the next skill to learn?**

I would like to gain more hands-on experience with next-generation sequencing (NGS) in the lab. So far, I’ve mainly worked with NGS data during the analysis phase, but I’m really interested in learning how to carry out the full process from sample preparation to library construction and running the sequencer. In addition to that, I’d like to strengthen other general lab skills to become more confident in an experimental setting. My goal is to better connect what happens in the lab to the data I analyze, so I can understand the full workflow from sample to result and make more informed decisions during analysis.
