# Guerrilla Analytics on DAUR2 course

## Directory tree

~/onedrive/documenten/daur2
├── metagenomics_species_identification
│   ├── data_bewerkt
│   │   ├── alignment_statistics.rds
│   │   ├── bracken
│   │   │   ├── mock1.bracken
│   │   │   └── mock2.bracken
│   │   ├── HU1_MOCK1_L001_R1_001_fastqc.html
│   │   ├── HU1_MOCK1_L001_R2_001_fastqc.html
│   │   ├── HU2_MOCK2_L001_R1_001_fastqc.html
│   │   ├── HU2_MOCK2_L001_R2_001_fastqc.html
│   │   └── kraken2
│   │       ├── mock1
│   │       │   ├── mock1.report
│   │       │   ├── mock1_bracken_species.biom
│   │       │   └── mock1_bracken_species.report
│   │       └── mock2
│   │           ├── mock2.report
│   │           ├── mock2_bracken_species.biom
│   │           └── mock2_bracken_species.report
│   ├── data_ruw
│   │   ├── HU1_MOCK1_L001_R1_001.fastq.gz
│   │   ├── HU1_MOCK1_L001_R2_001.fastq.gz
│   │   ├── HU2_MOCK2_L001_R1_001.fastq.gz
│   │   ├── HU2_MOCK2_L001_R2_001.fastq.gz
│   │   └── README.txt
│   ├── docs
│   │   └── setup_meta_env.yml
│   ├── results
│   │   ├── FASTQC_report_SRR7866699_1.png
│   │   ├── FASTQC_report_SRR7866701_2.png
│   │   ├── metagenomics_formatief.html
│   │   ├── mock2_R1_formatief.png
│   │   └── mock2_R2_formatief.png
│   └── scripts
│       ├── Metagenomics.Rmd
│       ├── metagenomics_formatief.Rmd
│       └── README.txt
├── rna_seq_eindopdracht
│   ├── data_bewerkt
│   │   ├── fastqc_output
│   │   │   ├── SRR7866687_1_fastqc.html
│   │   │   ├── SRR7866687_2_fastqc.html
│   │   │   ├── SRR7866688_1_fastqc.html
│   │   │   ├── SRR7866688_2_fastqc.html
│   │   │   ├── SRR7866689_1_fastqc.html
│   │   │   ├── SRR7866689_2_fastqc.html
│   │   │   ├── SRR7866690_1_fastqc.html
│   │   │   ├── SRR7866690_2_fastqc.html
│   │   │   ├── SRR7866691_1_fastqc.html
│   │   │   ├── SRR7866691_2_fastqc.html
│   │   │   ├── SRR7866692_1_fastqc.html
│   │   │   ├── SRR7866692_2_fastqc.html
│   │   │   ├── SRR7866693_1_fastqc.html
│   │   │   ├── SRR7866693_2_fastqc.html
│   │   │   ├── SRR7866694_1_fastqc.html
│   │   │   ├── SRR7866694_2_fastqc.html
│   │   │   ├── SRR7866699_1_fastqc.html
│   │   │   ├── SRR7866699_2_fastqc.html
│   │   │   ├── SRR7866700_1_fastqc.html
│   │   │   ├── SRR7866700_2_fastqc.html
│   │   │   ├── SRR7866701_1_fastqc.html
│   │   │   ├── SRR7866701_2_fastqc.html
│   │   │   ├── SRR7866702_1_fastqc.html
│   │   │   ├── SRR7866702_2_fastqc.html
│   │   │   ├── SRR7866703_1_fastqc.html
│   │   │   ├── SRR7866703_2_fastqc.html
│   │   │   ├── SRR7866704_1_fastqc.html
│   │   │   ├── SRR7866704_2_fastqc.html
│   │   │   ├── SRR7866705_1_fastqc.html
│   │   │   ├── SRR7866705_2_fastqc.html
│   │   │   ├── SRR7866706_1_fastqc.html
│   │   │   └── SRR7866706_2_fastqc.html
│   │   ├── gene_counts.tsv
│   │   ├── normalized_data.csv
│   │   └── README.txt
│   ├── data_ruw
│   │   ├── README.txt
│   │   ├── SRR7866687_1.fastq.gz
│   │   ├── SRR7866687_2.fastq.gz
│   │   ├── SRR7866688_1.fastq.gz
│   │   ├── SRR7866688_2.fastq.gz
│   │   ├── SRR7866689_1.fastq.gz
│   │   └── SRR7866689_2.fastq.gz
│   ├── docs
│   │   ├── project_description.md
│   │   └── README.txt
│   ├── results
│   │   ├── heatmap.pdf
│   │   ├── rna_seq_opdracht.html
│   │   └── volcano_plot.png
│   └── scripts
│       ├── analysis.Rmd
│       ├── preprocess.Rmd
│       └── rna_seq_opdracht.Rmd
└── rna_seq_odpracht
    ├── data_bewerkt
    │   ├── gene_counts.tsv
    │   ├── normalized_data.csv
    │   └── README.txt
    ├── data_ruw
    │   ├── raw_data_1.fastq.gz
    │   ├── raw_data_2.fastq.gz
    │   └── README.txt
    ├── docs
    │   ├── project_description.md
    │   └── README.txt
    ├── results
    │   ├── heatmap.pdf
    │   ├── rna_seq_opdracht.html
    │   └── volcano_plot.png
    └── scripts
        ├── analysis.Rmd
        ├── preprocess.Rmd
        └── rna_seq_opdracht.Rmd