YAML HEADER NOG TOEVOEGEN en een geheel ding maken

# Naam van hoofdstuk

   - The file contains mostly metadata with columns repeating this type of data.

  - flow_tidy <- read_excel("ruwe_data/CE.LIQ.FLOW.062_Tidydata.xlsx")
    View(flow_tidy)

   - RawData is of the class 'numeric' and compName is 'character' which are both correct. CompConcentration is also of the class 'character' which is not correct. It should be numerical and this is the code to change it to the right class: flow_tidy$compConcentration <- as.numeric(flow_tidy$compConcentration)
```{R, Loading the data}
library(readxl)

flow_tidy <- read_excel("ruwe_data/CE.LIQ.FLOW.062_Tidydata.xlsx")

```


D Create a graph displaying a scatterplot for the CE.LIQ.FLOW.062_Tidydata.xlsx data, for the different compounds and the varying concentrations. Put the compConcentration on the x-axis, the DataRaw counts on the y-axis and assign a colour to each level in compName. Assign a different symbol (shape =) to each level in the expType variable. Try fixing the labels of the x-axis so that we can read them.
```{r, scatterplot}
library(ggplot2)
library(tidyverse)
library(dplyr)

# Eindresultaat scatterplot:
#  - x-as compconentration --> goeie x-as labels
#  - y-as rawdata counts 
#     - + kleur per level in compname
#     - + andere shape per level in exptype


# Change comconcentration into numeric column.
flow_tidy$compConcentration <- as.numeric(flow_tidy$compConcentration)

#remove rows with NA
flow_tidy$plateRow <- NULL
flow_tidy$plateColumn <- NULL

# Change compname and exptype into factors
flow_tidy$compName <- as.factor(flow_tidy$compName)
flow_tidy$expType <-  as.factor(flow_tidy$expType)

#take the log10 value of the compConcentration
flow_tidy$logConcentration <-  log(flow_tidy$compConcentration, base = 10)

# Plot the data
flow_tidy_plot <- flow_tidy %>% ggplot(aes(x= logConcentration, y= RawData, colour = compName, shape = expType)) + geom_jitter() + theme_bw() + labs(title = "C.elegans nematodes exposed to varying concentrations of different compounds", x= "log10 of the concentration in nM")

print(flow_tidy_plot)
```


- The concentration of the compounds has a wide range which isn't good for visualisation in the scatterplot. To solve this problem, the log10 value of the compConcentration is used to make the scatterplot to reduce the datapoint being very far apart.

- Fill in: (G) The positive control for this experiments is Ethanol. (H) The negative control for this experiment is S-medium.

I Think about how you would analyze this experiment to learn whether there is indeed an effect of different concentrations on offspring count and whether the different compounds have a different curve (IC50). Write down you analysis as a step-wise plan.

- If this experiment was analyzed in a way to learn if there is indeed an effect of different concentrations on offspring count and whether the different compounds have a different effect. The following steps are neccesary:
1. volledig uitschrijven in stappen hoe je een dosisresponse curve maakt.

J Normalize the data for the controlNegative in such a way that the mean value for controlNegative is exactly equal to 1 and that all other values are expressed as a fraction thereof. Rerun your graphs with the normalized data.
- eerst ff de gemiddelde van negatieve controle en daarna dat van de normale waarden aftrekken en daarna de log?
- rij 1 tm 30 is negatieve controle

flow_tidy2 <- flow_tidy

Nu geen zin maak later af.

K Why would you want to take the step under J?